version: 3.0
services:
  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: true
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: rssreader
      INFLUXDB_USER_PASSWORD: rssreader
    ports:
      - "8086:8086"