version: 3.0
services:
  postgresql:
    image: postgres:13
    restart: always
    volumes:
     - "postgresql-persistent:/var/lib/postgresql/data"
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"